name: Main workflow

on:
  - pull_request
  - push

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macOS-latest
          - ubuntu-latest
        ocaml-compiler:
          - 4.8.x
          - 4.9.x
          - 4.10.x
          - 4.11.x
          - 4.12.x

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}

      - run: brew install supercollider
        if:  matrix.os == 'macOS-latest'

      - run: echo "/Applications/SuperCollider.app/Contents/MacOS" >> $GITHUB_PATH
        if:  matrix.os == 'macOS-latest'

      - run: sudo apt-get install -y supercollider-language
        if:  matrix.os == 'ubuntu-latest'

      - run: opam install . --deps-only --with-doc --with-test

      - run: opam exec -- dune build

      - run: opam exec -- dune runtest
